version: '3.7'

services:
  backend_api:
    build: .
    image: ${CONTAINER_NAMESPACE}:backend_api_${CONTAINER_VERSION}
    volumes:
      - ./backend:/app
    ports: 
      - 3000
    env_file: .env
  database:
    image: postgres:12-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
