version: '3'

services:
  backend_api:
    build: .
    image: ${CONTAINER_NAMESPACE}/backend:${CONTAINER_VERSION}
    ports: 
      - 3000
    env_file: .env
    command: rails s -b 0.0.0.0
  database:
    image: postgres:12-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
